#!/bin/bash
# 禁用APC缓存
echo 'php_value apc.cache_by_default off' > ${OPENSHIFT_REPO_DIR}.htaccess

# 下载签到程序并展开
cd ${OPENSHIFT_REPO_DIR}
curl -s http://git.oschina.net/sy/shuangya/repository/archive?ref=master > sign.zip
unzip sign.zip
rm -f ${OPENSHIFT_REPO_DIR}acfun.php
mv ${OPENSHIFT_REPO_DIR}acfun_normal.php ${OPENSHIFT_REPO_DIR}acfun.php
mv ${OPENSHIFT_REPO_DIR}shuangya/php/ACFun_sign/* ${OPENSHIFT_REPO_DIR}
rm -rf ${OPENSHIFT_REPO_DIR}sign.zip ${OPENSHIFT_REPO_DIR}shuangya

# 加入安装程序
cd ${OPENSHIFT_REPO_DIR}
cp -rf ${OPENSHIFT_REPO_DIR}.openshift/tools/install.php ${OPENSHIFT_REPO_DIR}